export const FOXHOLE_REGIONS = [
  "The Oarbreaker Isles",
  "Fisherman's Row",
  "Stema Landing",
  "Origin",
  "Ash Fields",
  "Westgate",
  "Sableport",
  "Loch Mór",
  "King's Cage",
  "Farranac Coast",
  "Stonecradle",
  "The Linn of Mercy",
  "Nevish Line",
  "Callum's Cape",
  "Speaking Woods",
  "Basin Sionnach",
  "Reaching Trail",
  "The Moors",
  "Callahan's Passage",
  "Deadlands",
  "Marban Hollow",
  "Viper Pit",
  "Weathered Expanse",
  "The Clahstra",
  "Stlican Shelf",
  "Morgan's Crossing",
  "Clanshead Valley",
  "Howl County",
  "Allod's Bight",
  "The Drowned Vale",
  "Umbral Wildwood",
  "Great March",
  "The Heartlands",
  "Red River",
  "Shackled Chasm",
  "Acrithia",
  "Kalokai",
  "Terminus",
  "Reaver's Pass",
  "The Fingers",
  "Endless Shore",
  "Tempest Island",
  "Godcrofts",
  "Warden Home Region",
  "Colonial Home Region"
] as const;

export const FOXHOLE_ISLANDS = new Set<string>(["Fisherman's Row", "Godcrofts", "Tempest Island", "The Fingers", "The Oarbreaker Isles"]);
